--------- beginning of main
12-06 14:05:38.008 14432 14457 I flutter : 00:35 +1 -2: pumpAndSettle failure caused by timeout of testWidgets [E]
12-06 14:05:38.010 14432 14457 I flutter :   TimeoutException after 0:00:10.000000: Test timed out after 10 seconds.
12-06 14:05:38.060 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 333:28  Invoker._handleError.<fn>
12-06 14:05:38.060 14432 14457 I flutter :   dart:async/zone.dart 1420:47                      _rootRun
12-06 14:05:38.060 14432 14457 I flutter :   dart:async/zone.dart 1328:19                      _CustomZone.run
12-06 14:05:38.060 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 331:10  Invoker._handleError
12-06 14:05:38.060 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 287:9   Invoker.heartbeat.<fn>.<fn>
12-06 14:05:38.060 14432 14457 I flutter :   dart:async/zone.dart 1428:13                      _rootRun
12-06 14:05:38.060 14432 14457 I flutter :   dart:async/zone.dart 1328:19                      _CustomZone.run
12-06 14:05:38.060 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 286:38  Invoker.heartbeat.<fn>
12-06 14:05:38.060 14432 14457 I flutter :   dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
12-06 14:05:38.060 14432 14457 I flutter :   dart:isolate-patch/timer_impl.dart 395:19         _Timer._runTimers
12-06 14:05:38.060 14432 14457 I flutter :   dart:isolate-patch/timer_impl.dart 426:5          _Timer._handleMessage
12-06 14:05:38.060 14432 14457 I flutter :   dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePortImpl._handleMessage
12-06 14:05:38.060 14432 14457 I flutter :   
12-06 14:05:38.060 14432 14457 I flutter : Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
12-06 14:05:38.060 14432 14457 I flutter : For example, 'dart test --chain-stack-traces'.
12-06 14:05:38.063 14432 14457 I flutter :   'package:flutter_test/src/binding.dart': Failed assertion: line 1690 pos 12: '_pendingFrame == null': is not true.
12-06 14:05:38.066 14432 14457 I flutter :   dart:core-patch/errors_patch.dart 46:39           _AssertionError._doThrowNew
12-06 14:05:38.066 14432 14457 I flutter :   dart:core-patch/errors_patch.dart 36:5            _AssertionError._throwNew
12-06 14:05:38.066 14432 14457 I flutter :   package:flutter_test/src/binding.dart 1690:12     LiveTestWidgetsFlutterBinding.postTest
12-06 14:05:38.066 14432 14457 I flutter :   dart:async/future.dart 218:31                     new Future.sync
12-06 14:05:38.066 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 236:18  Invoker.runTearDowns.<fn>.<fn>
12-06 14:05:38.066 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 257:15  Invoker._waitForOutstandingCallbacks.<fn>
12-06 14:05:38.066 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 254:14  Invoker._waitForOutstandingCallbacks.<fn>
12-06 14:05:38.066 14432 14457 I flutter :   dart:async/zone.dart 1428:13                      _rootRun
12-06 14:05:38.066 14432 14457 I flutter :   dart:async/zone.dart 1328:19                      _CustomZone.run
12-06 14:05:38.066 14432 14457 I flutter :   dart:async/zone.dart 1863:10                      _runZoned
12-06 14:05:38.066 14432 14457 I flutter :   dart:async/zone.dart 1785:10                      runZoned
12-06 14:05:38.066 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 254:5   Invoker._waitForOutstandingCallbacks
12-06 14:05:38.066 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 235:9   Invoker.runTearDowns.<fn>
12-06 14:05:38.066 14432 14457 I flutter :   package:test_a
12-06 14:05:38.066 14432 14457 I flutter : Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
12-06 14:05:38.066 14432 14457 I flutter : For example, 'dart test --chain-stack-traces'.
12-06 14:05:38.066 14432 14457 I flutter : 00:35 +1 -3: pumpAndSettle failure caused by defaultTestTimeout
12-06 14:05:38.071 14432 14457 I flutter : 00:35 +1 -3: pumpAndSettle failure caused by defaultTestTimeout [E]
12-06 14:05:38.071 14432 14457 I flutter :   'package:flutter_test/src/binding.dart': Failed assertion: line 1661 pos 12: '!inTest': is not true.
12-06 14:05:38.072 14432 14457 I flutter :   dart:core-patch/errors_patch.dart 46:39                _AssertionError._doThrowNew
12-06 14:05:38.072 14432 14457 I flutter :   dart:core-patch/errors_patch.dart 36:5                 _AssertionError._throwNew
12-06 14:05:38.072 14432 14457 I flutter :   package:flutter_test/src/binding.dart 1661:12          LiveTestWidgetsFlutterBinding.runTest
12-06 14:05:38.072 14432 14457 I flutter :   package:integration_test/integration_test.dart 219:17  IntegrationTestWidgetsFlutterBinding.runTest
12-06 14:05:38.072 14432 14457 I flutter :   package:flutter_test/src/widget_tester.dart 169:24     testWidgets.<fn>
12-06 14:05:38.072 14432 14457 I flutter :   package:test_api/src/backend/declarer.dart 199:19      Declarer.test.<fn>.<fn>
12-06 14:05:38.072 14432 14457 I flutter :   ===== asynchronous gap ===========================
12-06 14:05:38.072 14432 14457 I flutter :   package:test_api/src/backend/declarer.dart 197:7       Declarer.test.<fn>
12-06 14:05:38.072 14432 14457 I flutter :   ===== asynchronous gap ===========================
12-06 14:05:38.072 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 257:7        Invoker._waitForOutstandingCallbacks.<fn>
12-06 14:05:38.072 14432 14457 I flutter :   
12-06 14:05:38.072 14432 14457 I flutter : Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
12-06 14:05:38.072 14432 14457 I flutter : For example, 'dart test --chain-stack-traces'.
12-06 14:05:38.073 14432 14457 I flutter :   'package:flutter_test/src/binding.dart': Failed assertion: line 1689 pos 12: '!_expectingFrame': is not true.
12-06 14:05:38.074 14432 14457 I flutter :   dart:core-patch/errors_patch.dart 46:39           _AssertionError._doThrowNew
12-06 14:05:38.074 14432 14457 I flutter :   dart:core-patch/errors_patch.dart 36:5            _AssertionError._throwNew
12-06 14:05:38.074 14432 14457 I flutter :   package:flutter_test/src/binding.dart 1689:12     LiveTestWidgetsFlutterBinding.postTest
12-06 14:05:38.074 14432 14457 I flutter :   dart:async/future.dart 218:31                     new Future.sync
12-06 14:05:38.074 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 236:18  Invoker.runTearDowns.<fn>.<fn>
12-06 14:05:38.074 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 257:15  Invoker._waitForOutstandingCallbacks.<fn>
12-06 14:05:38.074 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 254:14  Invoker._waitForOutstandingCallbacks.<fn>
12-06 14:05:38.074 14432 14457 I flutter :   dart:async/zone.dart 1428:13                      _rootRun
12-06 14:05:38.074 14432 14457 I flutter :   dart:async/zone.dart 1328:19                      _CustomZone.run
12-06 14:05:38.074 14432 14457 I flutter :   dart:async/zone.dart 1863:10                      _runZoned
12-06 14:05:38.074 14432 14457 I flutter :   dart:async/zone.dart 1785:10                      runZoned
12-06 14:05:38.074 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 254:5   Invoker._waitForOutstandingCallbacks
12-06 14:05:38.074 14432 14457 I flutter :   package:test_api/src/backend/invoker.dart 235:9   Invoker.runTearDowns.<fn>
12-06 14:05:38.074 14432 14457 I flutter :   package:test_a
12-06 14:05:38.074 14432 14457 I flutter : Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
12-06 14:05:38.074 14432 14457 I flutter : For example, 'dart test --chain-stack-traces'.
12-06 14:05:38.074 14432 14457 I flutter : 00:35 +1 -4: (tearDownAll)
12-06 14:05:38.093 14432 14457 I flutter : 00:35 +2 -4: Some tests failed.
--------- beginning of system
